FROM electronuserland/builder:wine

ARG GIT_BRANCH=""

# Pull app source from git
RUN mkdir -p /opt \
  && cd /opt \
  && git clone --depth 1 --branch $GIT_BRANCH https://github.com/blocknetdx/xlite.git \
  && cd /opt/xlite \
  && mkdir -p dist-native

# Install app dependencies
RUN cd /opt/xlite \
  && npm install --no-audit

WORKDIR /opt/xlite/
VOLUME /opt/xlite/dist-native

ENTRYPOINT ["npm"]
CMD ["run", "publish-native-win"]
