name: Build and Publish Releases
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
      tag:
        description: 'version tag "1.0.4"'
        required: false
        default: '1.0.4'
      is_beta:
        description: 'Is it a beta release?'
        required: false
        default: false

jobs:
  build:
    name: Build and Publish
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.1

      - name: Install Dependencies
        run: npm install --no-audit

      - name: Download Binaries (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run download-binaries-linux

      - name: Download Binaries (Windows)
        if: startsWith(matrix.os, 'windows')
        run: npm run download-binaries-win

      - name: Download Binaries (macOS)
        if: startsWith(matrix.os, 'macos')
        run: npm run download-binaries-mac

      - name: Build Native Image (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: npm run build-native-linux-artifact

      - name: Build Native Image (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          npm run build-native-win-artifact
          del dist-native\XLite-${{ github.event.inputs.tag }}-win-x64.exe.blockmap

      - name: Build Native Image (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          npm run build-native-mac-artifact
          rm dist-native/XLite-${{ github.event.inputs.tag }}-mac.dmg.blockmap 
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist-native/XLite-${{ github.event.inputs.tag }}-*
          tag: ${{ github.event.inputs.tag }}
          overwrite: true
          prerelease: true
          file_glob: true
          body: "based on branch: ${{ github.event.inputs.branch }}"
